In [1]:
from glob import glob
import pandas as pd
import os
from shutil import copyfile

In [2]:
old_models_info = pd.read_csv("old_models_info.csv")
xgb_models_info = pd.read_csv("xgb_models_info.csv")

In [3]:
len(old_models_info), len(xgb_models_info)

(768, 864)

In [4]:
old_models_info.head()

,name,f1_score,roc_auc_score,total_actives,predicted_actives,version
0,transmembrane_protease_serine_11d,1.0,1.0,4,4,py35
1,farnesyl_pyrophosphate_synthase,1.0,1.0,36,36,py27
2,c3a_anaphylatoxin_chemotactic_receptor,1.0,1.0,5,5,py35
3,bombesin_receptor_subtype_3,1.0,1.0,24,24,py35
4,fatty_acid_desaturase_1,1.0,1.0,7,7,py27

In [5]:
xgb_models_info.head()

,model_name,f1,roc_auc,accuracy
0,15_hydroxyprostaglandin_dehydrogenase_nad_,0.928571,0.999333,0.996745
1,1_25_dihydroxyvitamin_d_3_24_hydroxylase_mitoc...,1.000000,1.000000,1.000000
2,1_acyl_sn_glycerol_3_phosphate_acyltransferase...,1.000000,1.000000,1.000000
3,2_acylglycerol_o_acyltransferase_2,0.967742,0.999848,0.998465
4,3_beta_hydroxysteroid_dehydrogenase_delta_5_4_...,0.888889,0.994624,0.989691

In [6]:
# Rename the models name column to match with the other dataframe
xgb_models_info = xgb_models_info.rename(index=str, columns={'model_name': 'name'})

In [7]:
common_df = pd.merge(old_models_info, xgb_models_info, how='inner', on='name')
common_df.head()

,name,f1_score,roc_auc_score,total_actives,predicted_actives,version,f1,roc_auc,accuracy
0,transmembrane_protease_serine_11d,1.0,1.0,4,4,py35,0.888889,1.000000,0.996785
1,farnesyl_pyrophosphate_synthase,1.0,1.0,36,36,py27,1.000000,1.000000,1.000000
2,c3a_anaphylatoxin_chemotactic_receptor,1.0,1.0,5,5,py35,1.000000,1.000000,1.000000
3,bombesin_receptor_subtype_3,1.0,1.0,24,24,py35,0.897959,0.999565,0.993679
4,fatty_acid_desaturase_1,1.0,1.0,7,7,py27,0.857143,0.997592,0.989189

In [8]:
good_old_models = common_df[common_df.f1_score > common_df.f1]
good_old_models.to_csv("good_old_models.csv", index=None)

In [9]:
old_models = []
xgb_models =[]

In [11]:
# copy good old models
count = 0
for _model in good_old_models.name:
    old_models.append(_model)
    if not os.path.isfile('bin/old_models/' + _model): print("{} NOT FOUND".format(_model))
    copyfile('bin/old_models/' + _model, 'models/' + _model)

In [12]:
# copy xgb models
count = 0
for _model in xgb_models_info[~xgb_models_info.name.isin(good_old_models.name)]['name']:
    if not os.path.isfile('bin/xgb_models/' + _model): 
        print("{} NOT FOUND".format(_model))
        continue
    xgb_models.append(_model)
    copyfile('bin/xgb_models/' + _model, 'models/' + _model)

In [31]:
# list the python 2.7 and python 3.5 models (crap!!!)
py35_models = xgb_models_info[~xgb_models_info.name.isin(good_old_models.name)]['name'].tolist()
py35_models.extend(good_old_models[good_old_models.version=='py35']['name'].tolist())

py27_models = good_old_models[good_old_models.version=='py27']['name'].tolist()

In [32]:
with open('py35_models.txt', 'w') as f:
    f.write(','.join(py35_models))

In [33]:
with open('py27_models.txt', 'w') as f:
    f.write(','.join(py27_models))

In [34]:
print("py35 models: {} and py27 models: {}".format(len(py35_models), len(py27_models)))

py35 models: 753 and py27 models: 111

In [35]:
len(xgb_models) + len(old_models)

865

In [14]:
# convert pickled xgb models to joblib models

In [17]:
from sklearn.externals import joblib
import pickle

In [22]:
for _model in xgb_models:
    model = pickle.load(open('models/' + _model, 'rb'))
    with open('xgb_joblib/'+_model, 'wb') as f:
        joblib.dump(model, f)
    #break

/home/mhassan/anaconda3/envs/dl/lib/python3.5/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator LabelEncoder from version 0.20.2 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

In [39]:
# test
py35_models = open('py35_models.txt', 'r').readlines()[0].split(',')

In [42]:
for _model in py35_models:
    joblib.load('models/' + _model)

/home/mhassan/anaconda3/envs/dl/lib/python3.5/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.18.1 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/home/mhassan/anaconda3/envs/dl/lib/python3.5/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.18.1 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/home/mhassan/anaconda3/envs/dl/lib/python3.5/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator SVC from version 0.18.1 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

In [43]:
# test to predict
import sys
sys.path.append("../ddt/")
from utility import FeatureGenerator

In [44]:
ft = FeatureGenerator()
ft.load_sdf("../ddt/samples/AAAAML.xaa.sdf")

In [56]:
def get_models(version='35'):
    model_names = open('py' + version + '_models.txt', 'r').readlines()[0].split(',')
    for model in model_names:
        yield model, joblib.load('models/' + model)

In [66]:
features = ft.extract_tpatf()
for model_name, model in get_models():
    if type(model).__name__ == "SVC": 
        predict = model.predict(features)
        if predict.any():
            print(model_name, predict)
    else:
        predict = model.predict_proba(features)
        conf_mask = predict[:, 1]>0.9
        print(predict[conf_mask])
    
    #break

[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[0.03089797 0.969102  ]
 [0.02369303 0.976307  ]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[0.00878769 0.9912123 ]
 [0.00878769 0.9912123 ]]
[[0.03521597 0.964784  ]
 [0.04526317 0.9547368 ]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[9.2879772e-02 9.0712023e-01]
 [9.4372034e-04 9.9905628e-01]
 [9.4372034e-04 9.9905628e-01]
 [9.4372034e-04 9.9905628e-01]
 [2.0657778e-03 9.9793422e-01]
 [8.5902214e-04 9.9914098e-01]
 [4.4864416e-04 9.9955136e-01]
 [9.4372034e-04 9.9905628e-01]]
[]
[]
[]
[]
[]
[]
[[0.00451684 0.99548316]
 [0.00451684 0.99548316]
 [0.00451684 0.99548316]
 [0.00451684 0.99548316]
 [0.00451684 0.99548316]
 [0.00451684 0.99548316]
 [0.00451684 0.99548316]
 [0.00451684 0.99548316]
 [0.00451684 0.99548316]
 [0.00451684 0.99548316]
 [0.00451684 0.99548316]
 [0.00451684 0.99548316]
 [0.00451684 0.99548316]]
[]
[]
[]
[]
[]
[[0.04274112 0.9572589 ]
 [0.04239851 0.9576015 ]
 [0.04344296 0.95655704]
 [0.07467812 0.9253219 ]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[0.05730098 0.942699  ]]
[]
[[0.03151762 0.9684824 ]
 [0.03151762 0.9684824 ]]
[]
[]
[]
[]
[]
[[7.3415041e-04 9.9926585e-01]]
[]
[]
[]
[]
[]
[[0.0327825 0.9672175]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[0.01089805 0.98910195]
 [0.06200367 0.9379963 ]
 [0.06200367 0.9379963 ]
 [0.06200367 0.9379963 ]
 [0.01481628 0.9851837 ]
 [0.01481628 0.9851837 ]
 [0.06200367 0.9379963 ]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[0.02808875 0.97191125]
 [0.02808875 0.97191125]]
[]
[[0.08628863 0.91371137]
 [0.08628863 0.91371137]
 [0.08628863 0.91371137]
 [0.08628863 0.91371137]]
[]
[]
[]
[]
[[0.0343256  0.9656744 ]
 [0.00674874 0.99325126]
 [0.00674874 0.99325126]
 [0.00674874 0.99325126]
 [0.08055854 0.91944146]
 [0.00674874 0.99325126]]
[]
[[0.0898295 0.9101705]
 [0.0898295 0.9101705]]
[[0.00273836 0.99726164]
 [0.00273836 0.99726164]
 [0.00273836 0.99726164]
 [0.00273836 0.99726164]
 [0.00273836 0.99726164]
 [0.00273836 0.99726164]
 [0.00273836 0.99726164]
 [0.00273836 0.99726164]
 [0.00273836 0.99726164]
 [0.00273836 0.99726164]
 [0.00273836 0.99726164]
 [0.00273836 0.99726164]
 [0.00273836 0.99726164]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[0.00700915 0.99299085]
 [0.01357532 0.9864247 ]
 [0.01614606 0.98385394]]
[]
[]
[]
[]
[]
[[0.08108246 0.91891754]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[0.01330799 0.986692  ]
 [0.01330799 0.986692  ]
 [0.0034011  0.9965989 ]
 [0.0034011  0.9965989 ]
 [0.0034011  0.9965989 ]
 [0.0034011  0.9965989 ]]
[]
[]
[[2.2464991e-04 9.9977535e-01]
 [2.2464991e-04 9.9977535e-01]
 [2.2464991e-04 9.9977535e-01]
 [2.2464991e-04 9.9977535e-01]]
[]
[[0.00588489 0.9941151 ]
 [0.01427853 0.98572147]
 [0.01466376 0.98533624]
 [0.01466376 0.98533624]
 [0.05446106 0.94553894]
 [0.05446106 0.94553894]
 [0.05446106 0.94553894]
 [0.01433426 0.98566574]
 [0.01433426 0.98566574]
 [0.05446106 0.94553894]
 [0.05446106 0.94553894]
 [0.05446106 0.94553894]
 [0.05446106 0.94553894]]
[]
[]
[]
[]
[]
[]
[[0.01230443 0.9876956 ]
 [0.01230443 0.9876956 ]
 [0.01230443 0.9876956 ]
 [0.01230443 0.9876956 ]
 [0.01230443 0.9876956 ]
 [0.01230443 0.9876956 ]]
[[0.00166047 0.99833953]
 [0.00166047 0.99833953]
 [0.00166047 0.99833953]
 [0.00166047 0.99833953]
 [0.00166047 0.99833953]
 [0.00166047 0.99833953]
 [0.00166047 0.99833953]
 [0.00166047 0.99833953]
 [0.00166047 0.99833953]
 [0.00166047 0.99833953]
 [0.00166047 0.99833953]
 [0.00166047 0.99833953]
 [0.00166047 0.99833953]]
[]
[]
[]
[]
[[0.04356599 0.956434  ]]
[[0.09886724 0.90113276]]
[]
[]
[]
[]
[[0.0855 0.9145]]
[]
[[0.06983089 0.9301691 ]
 [0.02425575 0.97574425]
 [0.06983089 0.9301691 ]]
[]
[[0.01768309 0.9823169 ]
 [0.01815879 0.9818412 ]]
[[0.06073034 0.93926966]
 [0.06073034 0.93926966]
 [0.06073034 0.93926966]
 [0.01376617 0.98623383]
 [0.06073034 0.93926966]
 [0.06073034 0.93926966]
 [0.06073034 0.93926966]]
[[0.0019061  0.9980939 ]
 [0.0019061  0.9980939 ]
 [0.0019061  0.9980939 ]
 [0.00466084 0.99533916]
 [0.00466084 0.99533916]
 [0.0019061  0.9980939 ]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[0.0044775  0.9955225 ]
 [0.05467427 0.94532573]
 [0.05467427 0.94532573]
 [0.05467427 0.94532573]
 [0.04370242 0.9562976 ]
 [0.04370242 0.9562976 ]
 [0.05467427 0.94532573]]
[[0.01733005 0.98266995]
 [0.04160368 0.9583963 ]]
[]
[[1.7821372e-02 9.8217863e-01]
 [9.1207027e-04 9.9908793e-01]
 [9.1207027e-04 9.9908793e-01]
 [9.1207027e-04 9.9908793e-01]
 [9.1207027e-04 9.9908793e-01]]
[]
[[0.00745302 0.992547  ]
 [0.00745302 0.992547  ]
 [0.00745302 0.992547  ]
 [0.00745302 0.992547  ]
 [0.00745302 0.992547  ]
 [0.00745302 0.992547  ]
 [0.00745302 0.992547  ]
 [0.00745302 0.992547  ]]
[]
[[0.00344539 0.9965546 ]
 [0.00344539 0.9965546 ]
 [0.00344539 0.9965546 ]
 [0.00344539 0.9965546 ]
 [0.00376505 0.99623495]
 [0.00376505 0.99623495]
 [0.00376505 0.99623495]
 [0.00719649 0.9928035 ]
 [0.00719649 0.9928035 ]
 [0.00376505 0.99623495]
 [0.00265098 0.997349  ]
 [0.00376505 0.99623495]
 [0.00376505 0.99623495]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[0.01849663 0.98150337]
 [0.03929007 0.9607099 ]
 [0.03932911 0.9606709 ]
 [0.03932911 0.9606709 ]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[0.07496101 0.925039  ]]
[[0.00745302 0.992547  ]
 [0.00745302 0.992547  ]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[0.06399626 0.93600374]]
[]
[]
[]
[]
[]
[]
[]
[[0.03364611 0.9663539 ]
 [0.03364611 0.9663539 ]
 [0.03364611 0.9663539 ]
 [0.03364611 0.9663539 ]
 [0.03364611 0.9663539 ]
 [0.03364611 0.9663539 ]
 [0.03364611 0.9663539 ]
 [0.03364611 0.9663539 ]
 [0.03364611 0.9663539 ]
 [0.03364611 0.9663539 ]
 [0.03364611 0.9663539 ]
 [0.03364611 0.9663539 ]
 [0.03364611 0.9663539 ]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[0.00288069 0.9971193 ]
 [0.00294411 0.9970559 ]
 [0.00294411 0.9970559 ]]
[]
[]
[]
[[0.02468503 0.975315  ]
 [0.05394846 0.94605154]
 [0.05394846 0.94605154]]
[]
[]
[]
[]
[]
[[0.07345527 0.9265447 ]
 [0.07345527 0.9265447 ]
 [0.07345527 0.9265447 ]
 [0.07345527 0.9265447 ]
 [0.07345527 0.9265447 ]]
[[0.06212795 0.93787205]
 [0.06212795 0.93787205]
 [0.06212795 0.93787205]
 [0.06212795 0.93787205]
 [0.06212795 0.93787205]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[0.06811458 0.9318854 ]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[0.06495768 0.9350423 ]]
[[0.03478068 0.9652193 ]]
[[0.07735062 0.9226494 ]
 [0.07735062 0.9226494 ]
 [0.07735062 0.9226494 ]
 [0.07735062 0.9226494 ]]
[]
[]
[]
[]
[]
[]
[]
[[0.00166047 0.99833953]
 [0.00166047 0.99833953]
 [0.00166047 0.99833953]
 [0.00166047 0.99833953]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[0.05990678 0.9400932 ]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[0.03359646 0.96640354]
 [0.03359646 0.96640354]
 [0.03359646 0.96640354]
 [0.03359646 0.96640354]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[0.00245315 0.99754685]
 [0.02482551 0.9751745 ]
 [0.09363943 0.90636057]
 [0.09363943 0.90636057]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[0.00494063 0.9950594 ]]
[]
[]
[]
[]
[[0.00102746 0.99897254]
 [0.00162065 0.99837935]]
[[0.0010069 0.9989931]
 [0.0010069 0.9989931]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[0.09792978 0.9020702 ]]
[]
[[0.0302164 0.9697836]]
[]
[[0.0233078  0.9766922 ]
 [0.06041461 0.9395854 ]
 [0.06041461 0.9395854 ]
 [0.01560032 0.9843997 ]
 [0.01560032 0.9843997 ]
 [0.01560032 0.9843997 ]
 [0.00348657 0.9965134 ]
 [0.00348657 0.9965134 ]
 [0.01553643 0.9844636 ]
 [0.01560032 0.9843997 ]
 [0.01553643 0.9844636 ]
 [0.01560032 0.9843997 ]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[0.00789148 0.9921085 ]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[0.04617536 0.95382464]
 [0.04617536 0.95382464]
 [0.04617536 0.95382464]
 [0.03252757 0.96747243]
 [0.02276462 0.9772354 ]
 [0.04617536 0.95382464]]
[]
[]
[]
[[0.04950517 0.9504948 ]]
[]

[]
[]
[]
[]
[]
[]
[]
[[0.00223351 0.9977665 ]
 [0.00331146 0.99668854]
 [0.00510448 0.9948955 ]
 [0.00510448 0.9948955 ]]
[]
[[0.02312654 0.97687346]
 [0.08421278 0.9157872 ]
 [0.08421278 0.9157872 ]
 [0.08421278 0.9157872 ]
 [0.08421278 0.9157872 ]]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[[0.0049547  0.9950453 ]
 [0.00638342 0.9936166 ]]
[]
[]

/home/mhassan/anaconda3/envs/dl/lib/python3.5/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.18.1 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/home/mhassan/anaconda3/envs/dl/lib/python3.5/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.18.1 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

[]
[]

/home/mhassan/anaconda3/envs/dl/lib/python3.5/site-packages/sklearn/base.py:311: UserWarning: Trying to unpickle estimator SVC from version 0.18.1 when using version 0.19.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
lysine_specific_demethylase_5c [1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0.]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]